/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Login user
     * @description Authenticate user with username and password
     */
    post: operations['loginUser']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get current user
     * @description Get authenticated user information
     */
    get: operations['getCurrentUser']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/auth/refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Refresh token
     * @description Refresh access token using refresh token
     */
    post: operations['refreshToken']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get all users
     * @description Retrieve a list of all users with pagination
     */
    get: operations['getAllUsers']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/add': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Add a new user
     * @description Create a new user (simulated, not persisted)
     */
    post: operations['addUser']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/search': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Search users
     * @description Search users by query string
     */
    get: operations['searchUsers']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/filter': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Filter users
     * @description Filter users by key-value pair
     */
    get: operations['filterUsers']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get user by ID
     * @description Retrieve a single user by ID
     */
    get: operations['getUserById']
    /**
     * Update user
     * @description Update user by ID (simulated)
     */
    put: operations['updateUser']
    post?: never
    /**
     * Delete user
     * @description Delete user by ID (simulated)
     */
    delete: operations['deleteUser']
    options?: never
    head?: never
    /**
     * Partial update user
     * @description Partially update user by ID (simulated)
     */
    patch: operations['patchUser']
    trace?: never
  }
  '/users/{userId}/carts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get user carts
     * @description Get all carts belonging to a user
     */
    get: operations['getUserCarts']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/{userId}/posts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get user posts
     * @description Get all posts belonging to a user
     */
    get: operations['getUserPosts']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/{userId}/todos': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get user todos
     * @description Get all todos belonging to a user
     */
    get: operations['getUserTodos']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/products': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get all products
     * @description Retrieve a list of all products with pagination
     */
    get: operations['getAllProducts']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/products/add': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Add a new product
     * @description Create a new product (simulated)
     */
    post: operations['addProduct']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/products/search': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Search products
     * @description Search products by query string
     */
    get: operations['searchProducts']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/products/categories': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get product categories
     * @description Get all product categories with URLs
     */
    get: operations['getProductCategories']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/products/category-list': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get category list
     * @description Get list of category names
     */
    get: operations['getCategoryList']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/products/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get product by ID
     * @description Retrieve a single product by ID
     */
    get: operations['getProductById']
    /**
     * Update product
     * @description Update product by ID (simulated)
     */
    put: operations['updateProduct']
    post?: never
    /**
     * Delete product
     * @description Delete product by ID (simulated)
     */
    delete: operations['deleteProduct']
    options?: never
    head?: never
    /**
     * Partial update product
     * @description Partially update product by ID (simulated)
     */
    patch: operations['patchProduct']
    trace?: never
  }
  '/products/category/{categoryName}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get products by category
     * @description Retrieve products by category name
     */
    get: operations['getProductsByCategory']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/posts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get all posts
     * @description Retrieve a list of all posts with pagination
     */
    get: operations['getAllPosts']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/posts/add': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Add a new post
     * @description Create a new post (simulated)
     */
    post: operations['addPost']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/posts/search': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Search posts
     * @description Search posts by query string
     */
    get: operations['searchPosts']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/posts/tags': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get post tags
     * @description Get all post tags with URLs
     */
    get: operations['getPostTags']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/posts/tag-list': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get tag list
     * @description Get list of tag names
     */
    get: operations['getTagList']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/posts/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get post by ID
     * @description Retrieve a single post by ID
     */
    get: operations['getPostById']
    /**
     * Update post
     * @description Update post by ID (simulated)
     */
    put: operations['updatePost']
    post?: never
    /**
     * Delete post
     * @description Delete post by ID (simulated)
     */
    delete: operations['deletePost']
    options?: never
    head?: never
    /** Partial update post */
    patch: operations['patchPost']
    trace?: never
  }
  '/posts/tag/{tag}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get posts by tag
     * @description Retrieve posts by tag name
     */
    get: operations['getPostsByTag']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/posts/user/{userId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get posts by user
     * @description Retrieve posts by user ID
     */
    get: operations['getPostsByUser']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/posts/{postId}/comments': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get post comments
     * @description Get all comments for a post
     */
    get: operations['getPostComments']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/comments': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get all comments
     * @description Retrieve a list of all comments with pagination
     */
    get: operations['getAllComments']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/comments/add': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Add a new comment
     * @description Create a new comment (simulated)
     */
    post: operations['addComment']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/comments/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get comment by ID
     * @description Retrieve a single comment by ID
     */
    get: operations['getCommentById']
    /** Update comment */
    put: operations['updateComment']
    post?: never
    /** Delete comment */
    delete: operations['deleteComment']
    options?: never
    head?: never
    /** Partial update comment */
    patch: operations['patchComment']
    trace?: never
  }
  '/comments/post/{postId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get comments by post
     * @description Retrieve comments by post ID
     */
    get: operations['getCommentsByPost']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/carts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get all carts
     * @description Retrieve a list of all carts with pagination
     */
    get: operations['getAllCarts']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/carts/add': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Add a new cart
     * @description Create a new cart (simulated)
     */
    post: operations['addCart']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/carts/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get cart by ID
     * @description Retrieve a single cart by ID
     */
    get: operations['getCartById']
    /** Update cart */
    put: operations['updateCart']
    post?: never
    /** Delete cart */
    delete: operations['deleteCart']
    options?: never
    head?: never
    /** Partial update cart */
    patch: operations['patchCart']
    trace?: never
  }
  '/carts/user/{userId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get carts by user
     * @description Retrieve carts by user ID
     */
    get: operations['getCartsByUser']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/todos': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get all todos
     * @description Retrieve a list of all todos with pagination
     */
    get: operations['getAllTodos']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/todos/add': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Add a new todo
     * @description Create a new todo (simulated)
     */
    post: operations['addTodo']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/todos/random': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get random todo
     * @description Get a random todo
     */
    get: operations['getRandomTodo']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/todos/random/{length}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get random todos
     * @description Get multiple random todos
     */
    get: operations['getRandomTodos']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/todos/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get todo by ID
     * @description Retrieve a single todo by ID
     */
    get: operations['getTodoById']
    /** Update todo */
    put: operations['updateTodo']
    post?: never
    /** Delete todo */
    delete: operations['deleteTodo']
    options?: never
    head?: never
    /** Partial update todo */
    patch: operations['patchTodo']
    trace?: never
  }
  '/todos/user/{userId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get todos by user
     * @description Retrieve todos by user ID
     */
    get: operations['getTodosByUser']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/quotes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get all quotes
     * @description Retrieve a list of all quotes with pagination
     */
    get: operations['getAllQuotes']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/quotes/random': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get random quote
     * @description Get a random quote
     */
    get: operations['getRandomQuote']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/quotes/random/{length}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get random quotes
     * @description Get multiple random quotes
     */
    get: operations['getRandomQuotes']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/quotes/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get quote by ID
     * @description Retrieve a single quote by ID
     */
    get: operations['getQuoteById']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/recipes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get all recipes
     * @description Retrieve a list of all recipes with pagination
     */
    get: operations['getAllRecipes']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/recipes/add': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Add a new recipe
     * @description Create a new recipe (simulated)
     */
    post: operations['addRecipe']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/recipes/search': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Search recipes
     * @description Search recipes by query string
     */
    get: operations['searchRecipes']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/recipes/tags': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get recipe tags
     * @description Get all recipe tags
     */
    get: operations['getRecipeTags']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/recipes/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get recipe by ID
     * @description Retrieve a single recipe by ID
     */
    get: operations['getRecipeById']
    /** Update recipe */
    put: operations['updateRecipe']
    post?: never
    /** Delete recipe */
    delete: operations['deleteRecipe']
    options?: never
    head?: never
    /** Partial update recipe */
    patch: operations['patchRecipe']
    trace?: never
  }
  '/recipes/tag/{tag}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get recipes by tag
     * @description Retrieve recipes by tag name
     */
    get: operations['getRecipesByTag']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/recipes/meal-type/{mealType}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get recipes by meal type
     * @description Retrieve recipes by meal type
     */
    get: operations['getRecipesByMealType']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/test': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health check
     * @description API health check endpoint
     */
    get: operations['healthCheck']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/image/{size}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Generate placeholder image
     * @description Generate a placeholder image with custom size
     */
    get: operations['generateImage']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/icon/{hash}/{size}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Generate identicon
     * @description Generate a unique identicon based on hash
     */
    get: operations['generateIcon']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    LoginRequest: {
      /** @example emilys */
      username: string
      /** @example emilyspass */
      password: string
      /** @default 60 */
      expiresInMins: number
    }
    AuthResponse: {
      id?: number
      username?: string
      email?: string
      firstName?: string
      lastName?: string
      gender?: string
      image?: string
      accessToken?: string
      refreshToken?: string
    }
    User: {
      id?: number
      firstName?: string
      lastName?: string
      maidenName?: string
      age?: number
      /** @enum {string} */
      gender?: 'male' | 'female'
      /** Format: email */
      email?: string
      phone?: string
      username?: string
      password?: string
      /** Format: date */
      birthDate?: string
      /** Format: uri */
      image?: string
      bloodGroup?: string
      height?: number
      weight?: number
      eyeColor?: string
      hair?: components['schemas']['Hair']
      ip?: string
      address?: components['schemas']['Address']
      macAddress?: string
      university?: string
      bank?: components['schemas']['Bank']
      company?: components['schemas']['Company']
      ein?: string
      ssn?: string
      userAgent?: string
      crypto?: components['schemas']['Crypto']
      /** @enum {string} */
      role?: 'admin' | 'moderator' | 'user'
    }
    UserInput: {
      firstName?: string
      lastName?: string
      age?: number
      /** Format: email */
      email?: string
    }
    UsersResponse: {
      users?: components['schemas']['User'][]
      total?: number
      skip?: number
      limit?: number
    }
    Hair: {
      color?: string
      type?: string
    }
    Address: {
      address?: string
      city?: string
      state?: string
      stateCode?: string
      postalCode?: string
      coordinates?: components['schemas']['Coordinates']
      country?: string
    }
    Coordinates: {
      lat?: number
      lng?: number
    }
    Bank: {
      cardExpire?: string
      cardNumber?: string
      cardType?: string
      currency?: string
      iban?: string
    }
    Company: {
      department?: string
      name?: string
      title?: string
      address?: components['schemas']['Address']
    }
    Crypto: {
      coin?: string
      wallet?: string
      network?: string
    }
    Product: {
      id?: number
      title?: string
      description?: string
      category?: string
      price?: number
      discountPercentage?: number
      rating?: number
      stock?: number
      tags?: string[]
      brand?: string
      sku?: string
      weight?: number
      dimensions?: components['schemas']['Dimensions']
      warrantyInformation?: string
      shippingInformation?: string
      availabilityStatus?: string
      reviews?: components['schemas']['Review'][]
      returnPolicy?: string
      minimumOrderQuantity?: number
      meta?: components['schemas']['ProductMeta']
      images?: string[]
      /** Format: uri */
      thumbnail?: string
    }
    ProductInput: {
      title?: string
      description?: string
      category?: string
      price?: number
      stock?: number
      brand?: string
    }
    ProductsResponse: {
      products?: components['schemas']['Product'][]
      total?: number
      skip?: number
      limit?: number
    }
    Dimensions: {
      width?: number
      height?: number
      depth?: number
    }
    Review: {
      rating?: number
      comment?: string
      /** Format: date-time */
      date?: string
      reviewerName?: string
      /** Format: email */
      reviewerEmail?: string
    }
    ProductMeta: {
      /** Format: date-time */
      createdAt?: string
      /** Format: date-time */
      updatedAt?: string
      barcode?: string
      /** Format: uri */
      qrCode?: string
    }
    Category: {
      slug?: string
      name?: string
      /** Format: uri */
      url?: string
    }
    Post: {
      id?: number
      title?: string
      body?: string
      tags?: string[]
      reactions?: components['schemas']['Reactions']
      views?: number
      userId?: number
    }
    PostInput: {
      title?: string
      body?: string
      userId?: number
      tags?: string[]
    }
    PostsResponse: {
      posts?: components['schemas']['Post'][]
      total?: number
      skip?: number
      limit?: number
    }
    Reactions: {
      likes?: number
      dislikes?: number
    }
    Tag: {
      slug?: string
      name?: string
      /** Format: uri */
      url?: string
    }
    Comment: {
      id?: number
      body?: string
      postId?: number
      likes?: number
      user?: components['schemas']['CommentUser']
    }
    CommentUser: {
      id?: number
      username?: string
      fullName?: string
    }
    CommentInput: {
      body?: string
      postId?: number
      userId?: number
    }
    CommentsResponse: {
      comments?: components['schemas']['Comment'][]
      total?: number
      skip?: number
      limit?: number
    }
    Cart: {
      id?: number
      products?: components['schemas']['CartProduct'][]
      total?: number
      discountedTotal?: number
      userId?: number
      totalProducts?: number
      totalQuantity?: number
    }
    CartProduct: {
      id?: number
      title?: string
      price?: number
      quantity?: number
      total?: number
      discountPercentage?: number
      discountedTotal?: number
      /** Format: uri */
      thumbnail?: string
    }
    CartInput: {
      userId?: number
      products?: {
        id?: number
        quantity?: number
      }[]
    }
    CartsResponse: {
      carts?: components['schemas']['Cart'][]
      total?: number
      skip?: number
      limit?: number
    }
    Todo: {
      id?: number
      todo?: string
      completed?: boolean
      userId?: number
    }
    TodoInput: {
      todo?: string
      completed?: boolean
      userId?: number
    }
    TodosResponse: {
      todos?: components['schemas']['Todo'][]
      total?: number
      skip?: number
      limit?: number
    }
    Quote: {
      id?: number
      quote?: string
      author?: string
    }
    QuotesResponse: {
      quotes?: components['schemas']['Quote'][]
      total?: number
      skip?: number
      limit?: number
    }
    Recipe: {
      id?: number
      name?: string
      ingredients?: string[]
      instructions?: string[]
      prepTimeMinutes?: number
      cookTimeMinutes?: number
      servings?: number
      /** @enum {string} */
      difficulty?: 'Easy' | 'Medium' | 'Hard'
      cuisine?: string
      caloriesPerServing?: number
      tags?: string[]
      userId?: number
      /** Format: uri */
      image?: string
      rating?: number
      reviewCount?: number
      mealType?: string[]
    }
    RecipeInput: {
      name?: string
      ingredients?: string[]
      instructions?: string[]
      prepTimeMinutes?: number
      cookTimeMinutes?: number
      servings?: number
      difficulty?: string
      cuisine?: string
    }
    RecipesResponse: {
      recipes?: components['schemas']['Recipe'][]
      total?: number
      skip?: number
      limit?: number
    }
  }
  responses: never
  parameters: {
    /** @description Resource ID */
    idParam: number
    /** @description Limit the number of items returned (default: 30) */
    limitParam: number
    /** @description Skip a number of items for pagination */
    skipParam: number
    /** @description Select specific fields (comma-separated) */
    selectParam: string
    /** @description Field to sort by */
    sortByParam: string
    /** @description Sort order */
    orderParam: 'asc' | 'desc'
    /** @description Search query string */
    searchParam: string
  }
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  loginUser: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description Login credentials */
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description Successful login */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuthResponse']
        }
      }
      /** @description Invalid credentials */
      400: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  getCurrentUser: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  refreshToken: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          refreshToken: string
          /** @default 60 */
          expiresInMins?: number
        }
      }
    }
    responses: {
      /** @description Token refreshed */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AuthResponse']
        }
      }
    }
  }
  getAllUsers: {
    parameters: {
      query?: {
        /** @description Limit the number of items returned (default: 30) */
        limit?: components['parameters']['limitParam']
        /** @description Skip a number of items for pagination */
        skip?: components['parameters']['skipParam']
        /** @description Select specific fields (comma-separated) */
        select?: components['parameters']['selectParam']
        /** @description Field to sort by */
        sortBy?: components['parameters']['sortByParam']
        /** @description Sort order */
        order?: components['parameters']['orderParam']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UsersResponse']
        }
      }
    }
  }
  addUser: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description User object */
    requestBody: {
      content: {
        'application/json': components['schemas']['UserInput']
      }
    }
    responses: {
      /** @description User created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
    }
  }
  searchUsers: {
    parameters: {
      query?: {
        /** @description Search query string */
        q?: components['parameters']['searchParam']
        /** @description Limit the number of items returned (default: 30) */
        limit?: components['parameters']['limitParam']
        /** @description Skip a number of items for pagination */
        skip?: components['parameters']['skipParam']
        /** @description Select specific fields (comma-separated) */
        select?: components['parameters']['selectParam']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UsersResponse']
        }
      }
    }
  }
  filterUsers: {
    parameters: {
      query?: {
        /** @description Field name to filter by */
        key?: string
        /** @description Value to filter */
        value?: string
        /** @description Limit the number of items returned (default: 30) */
        limit?: components['parameters']['limitParam']
        /** @description Skip a number of items for pagination */
        skip?: components['parameters']['skipParam']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UsersResponse']
        }
      }
    }
  }
  getUserById: {
    parameters: {
      query?: {
        /** @description Select specific fields (comma-separated) */
        select?: components['parameters']['selectParam']
      }
      header?: never
      path: {
        /** @description Resource ID */
        id: components['parameters']['idParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
      /** @description User not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  updateUser: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Resource ID */
        id: components['parameters']['idParam']
      }
      cookie?: never
    }
    /** @description User object */
    requestBody: {
      content: {
        'application/json': components['schemas']['UserInput']
      }
    }
    responses: {
      /** @description User updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
    }
  }
  deleteUser: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Resource ID */
        id: components['parameters']['idParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description User deleted */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
    }
  }
  patchUser: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Resource ID */
        id: components['parameters']['idParam']
      }
      cookie?: never
    }
    /** @description Partial user object */
    requestBody: {
      content: {
        'application/json': components['schemas']['UserInput']
      }
    }
    responses: {
      /** @description User updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['User']
        }
      }
    }
  }
  getUserCarts: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description User ID */
        userId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CartsResponse']
        }
      }
    }
  }
  getUserPosts: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description User ID */
        userId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PostsResponse']
        }
      }
    }
  }
  getUserTodos: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description User ID */
        userId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TodosResponse']
        }
      }
    }
  }
  getAllProducts: {
    parameters: {
      query?: {
        /** @description Limit the number of items returned (default: 30) */
        limit?: components['parameters']['limitParam']
        /** @description Skip a number of items for pagination */
        skip?: components['parameters']['skipParam']
        /** @description Select specific fields (comma-separated) */
        select?: components['parameters']['selectParam']
        /** @description Field to sort by */
        sortBy?: components['parameters']['sortByParam']
        /** @description Sort order */
        order?: components['parameters']['orderParam']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProductsResponse']
        }
      }
    }
  }
  addProduct: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** @description Product object */
    requestBody: {
      content: {
        'application/json': components['schemas']['ProductInput']
      }
    }
    responses: {
      /** @description Product created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Product']
        }
      }
    }
  }
  searchProducts: {
    parameters: {
      query?: {
        /** @description Search query string */
        q?: components['parameters']['searchParam']
        /** @description Limit the number of items returned (default: 30) */
        limit?: components['parameters']['limitParam']
        /** @description Skip a number of items for pagination */
        skip?: components['parameters']['skipParam']
        /** @description Select specific fields (comma-separated) */
        select?: components['parameters']['selectParam']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProductsResponse']
        }
      }
    }
  }
  getProductCategories: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Category'][]
        }
      }
    }
  }
  getCategoryList: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': string[]
        }
      }
    }
  }
  getProductById: {
    parameters: {
      query?: {
        /** @description Select specific fields (comma-separated) */
        select?: components['parameters']['selectParam']
      }
      header?: never
      path: {
        /** @description Resource ID */
        id: components['parameters']['idParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Product']
        }
      }
      /** @description Product not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  updateProduct: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Resource ID */
        id: components['parameters']['idParam']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ProductInput']
      }
    }
    responses: {
      /** @description Product updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Product']
        }
      }
    }
  }
  deleteProduct: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Resource ID */
        id: components['parameters']['idParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Product deleted */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Product']
        }
      }
    }
  }
  patchProduct: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Resource ID */
        id: components['parameters']['idParam']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ProductInput']
      }
    }
    responses: {
      /** @description Product updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Product']
        }
      }
    }
  }
  getProductsByCategory: {
    parameters: {
      query?: {
        /** @description Limit the number of items returned (default: 30) */
        limit?: components['parameters']['limitParam']
        /** @description Skip a number of items for pagination */
        skip?: components['parameters']['skipParam']
      }
      header?: never
      path: {
        /** @description Category name */
        categoryName: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProductsResponse']
        }
      }
    }
  }
  getAllPosts: {
    parameters: {
      query?: {
        /** @description Limit the number of items returned (default: 30) */
        limit?: components['parameters']['limitParam']
        /** @description Skip a number of items for pagination */
        skip?: components['parameters']['skipParam']
        /** @description Select specific fields (comma-separated) */
        select?: components['parameters']['selectParam']
        /** @description Field to sort by */
        sortBy?: components['parameters']['sortByParam']
        /** @description Sort order */
        order?: components['parameters']['orderParam']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PostsResponse']
        }
      }
    }
  }
  addPost: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PostInput']
      }
    }
    responses: {
      /** @description Post created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Post']
        }
      }
    }
  }
  searchPosts: {
    parameters: {
      query?: {
        /** @description Search query string */
        q?: components['parameters']['searchParam']
        /** @description Limit the number of items returned (default: 30) */
        limit?: components['parameters']['limitParam']
        /** @description Skip a number of items for pagination */
        skip?: components['parameters']['skipParam']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PostsResponse']
        }
      }
    }
  }
  getPostTags: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Tag'][]
        }
      }
    }
  }
  getTagList: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': string[]
        }
      }
    }
  }
  getPostById: {
    parameters: {
      query?: {
        /** @description Select specific fields (comma-separated) */
        select?: components['parameters']['selectParam']
      }
      header?: never
      path: {
        /** @description Resource ID */
        id: components['parameters']['idParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Post']
        }
      }
      /** @description Post not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  updatePost: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Resource ID */
        id: components['parameters']['idParam']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PostInput']
      }
    }
    responses: {
      /** @description Post updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Post']
        }
      }
    }
  }
  deletePost: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Resource ID */
        id: components['parameters']['idParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Post deleted */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Post']
        }
      }
    }
  }
  patchPost: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Resource ID */
        id: components['parameters']['idParam']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PostInput']
      }
    }
    responses: {
      /** @description Post updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Post']
        }
      }
    }
  }
  getPostsByTag: {
    parameters: {
      query?: {
        /** @description Limit the number of items returned (default: 30) */
        limit?: components['parameters']['limitParam']
        /** @description Skip a number of items for pagination */
        skip?: components['parameters']['skipParam']
      }
      header?: never
      path: {
        /** @description Tag name */
        tag: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PostsResponse']
        }
      }
    }
  }
  getPostsByUser: {
    parameters: {
      query?: {
        /** @description Limit the number of items returned (default: 30) */
        limit?: components['parameters']['limitParam']
        /** @description Skip a number of items for pagination */
        skip?: components['parameters']['skipParam']
      }
      header?: never
      path: {
        /** @description User ID */
        userId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PostsResponse']
        }
      }
    }
  }
  getPostComments: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Post ID */
        postId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CommentsResponse']
        }
      }
    }
  }
  getAllComments: {
    parameters: {
      query?: {
        /** @description Limit the number of items returned (default: 30) */
        limit?: components['parameters']['limitParam']
        /** @description Skip a number of items for pagination */
        skip?: components['parameters']['skipParam']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CommentsResponse']
        }
      }
    }
  }
  addComment: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CommentInput']
      }
    }
    responses: {
      /** @description Comment created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Comment']
        }
      }
    }
  }
  getCommentById: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Resource ID */
        id: components['parameters']['idParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Comment']
        }
      }
      /** @description Comment not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  updateComment: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Resource ID */
        id: components['parameters']['idParam']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CommentInput']
      }
    }
    responses: {
      /** @description Comment updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Comment']
        }
      }
    }
  }
  deleteComment: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Resource ID */
        id: components['parameters']['idParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Comment deleted */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Comment']
        }
      }
    }
  }
  patchComment: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Resource ID */
        id: components['parameters']['idParam']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CommentInput']
      }
    }
    responses: {
      /** @description Comment updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Comment']
        }
      }
    }
  }
  getCommentsByPost: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Post ID */
        postId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CommentsResponse']
        }
      }
    }
  }
  getAllCarts: {
    parameters: {
      query?: {
        /** @description Limit the number of items returned (default: 30) */
        limit?: components['parameters']['limitParam']
        /** @description Skip a number of items for pagination */
        skip?: components['parameters']['skipParam']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CartsResponse']
        }
      }
    }
  }
  addCart: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CartInput']
      }
    }
    responses: {
      /** @description Cart created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Cart']
        }
      }
    }
  }
  getCartById: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Resource ID */
        id: components['parameters']['idParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Cart']
        }
      }
      /** @description Cart not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  updateCart: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Resource ID */
        id: components['parameters']['idParam']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CartInput']
      }
    }
    responses: {
      /** @description Cart updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Cart']
        }
      }
    }
  }
  deleteCart: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Resource ID */
        id: components['parameters']['idParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Cart deleted */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Cart']
        }
      }
    }
  }
  patchCart: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Resource ID */
        id: components['parameters']['idParam']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CartInput']
      }
    }
    responses: {
      /** @description Cart updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Cart']
        }
      }
    }
  }
  getCartsByUser: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description User ID */
        userId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CartsResponse']
        }
      }
    }
  }
  getAllTodos: {
    parameters: {
      query?: {
        /** @description Limit the number of items returned (default: 30) */
        limit?: components['parameters']['limitParam']
        /** @description Skip a number of items for pagination */
        skip?: components['parameters']['skipParam']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TodosResponse']
        }
      }
    }
  }
  addTodo: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TodoInput']
      }
    }
    responses: {
      /** @description Todo created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Todo']
        }
      }
    }
  }
  getRandomTodo: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Todo']
        }
      }
    }
  }
  getRandomTodos: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Number of random todos */
        length: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Todo'][]
        }
      }
    }
  }
  getTodoById: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Resource ID */
        id: components['parameters']['idParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Todo']
        }
      }
      /** @description Todo not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  updateTodo: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Resource ID */
        id: components['parameters']['idParam']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TodoInput']
      }
    }
    responses: {
      /** @description Todo updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Todo']
        }
      }
    }
  }
  deleteTodo: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Resource ID */
        id: components['parameters']['idParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Todo deleted */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Todo']
        }
      }
    }
  }
  patchTodo: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Resource ID */
        id: components['parameters']['idParam']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TodoInput']
      }
    }
    responses: {
      /** @description Todo updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Todo']
        }
      }
    }
  }
  getTodosByUser: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description User ID */
        userId: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TodosResponse']
        }
      }
    }
  }
  getAllQuotes: {
    parameters: {
      query?: {
        /** @description Limit the number of items returned (default: 30) */
        limit?: components['parameters']['limitParam']
        /** @description Skip a number of items for pagination */
        skip?: components['parameters']['skipParam']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['QuotesResponse']
        }
      }
    }
  }
  getRandomQuote: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Quote']
        }
      }
    }
  }
  getRandomQuotes: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Number of random quotes */
        length: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Quote'][]
        }
      }
    }
  }
  getQuoteById: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Resource ID */
        id: components['parameters']['idParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Quote']
        }
      }
      /** @description Quote not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  getAllRecipes: {
    parameters: {
      query?: {
        /** @description Limit the number of items returned (default: 30) */
        limit?: components['parameters']['limitParam']
        /** @description Skip a number of items for pagination */
        skip?: components['parameters']['skipParam']
        /** @description Select specific fields (comma-separated) */
        select?: components['parameters']['selectParam']
        /** @description Field to sort by */
        sortBy?: components['parameters']['sortByParam']
        /** @description Sort order */
        order?: components['parameters']['orderParam']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RecipesResponse']
        }
      }
    }
  }
  addRecipe: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RecipeInput']
      }
    }
    responses: {
      /** @description Recipe created */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Recipe']
        }
      }
    }
  }
  searchRecipes: {
    parameters: {
      query?: {
        /** @description Search query string */
        q?: components['parameters']['searchParam']
        /** @description Limit the number of items returned (default: 30) */
        limit?: components['parameters']['limitParam']
        /** @description Skip a number of items for pagination */
        skip?: components['parameters']['skipParam']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RecipesResponse']
        }
      }
    }
  }
  getRecipeTags: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': string[]
        }
      }
    }
  }
  getRecipeById: {
    parameters: {
      query?: {
        /** @description Select specific fields (comma-separated) */
        select?: components['parameters']['selectParam']
      }
      header?: never
      path: {
        /** @description Resource ID */
        id: components['parameters']['idParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Recipe']
        }
      }
      /** @description Recipe not found */
      404: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  updateRecipe: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Resource ID */
        id: components['parameters']['idParam']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RecipeInput']
      }
    }
    responses: {
      /** @description Recipe updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Recipe']
        }
      }
    }
  }
  deleteRecipe: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Resource ID */
        id: components['parameters']['idParam']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Recipe deleted */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Recipe']
        }
      }
    }
  }
  patchRecipe: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Resource ID */
        id: components['parameters']['idParam']
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RecipeInput']
      }
    }
    responses: {
      /** @description Recipe updated */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Recipe']
        }
      }
    }
  }
  getRecipesByTag: {
    parameters: {
      query?: {
        /** @description Limit the number of items returned (default: 30) */
        limit?: components['parameters']['limitParam']
        /** @description Skip a number of items for pagination */
        skip?: components['parameters']['skipParam']
      }
      header?: never
      path: {
        /** @description Tag name */
        tag: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RecipesResponse']
        }
      }
    }
  }
  getRecipesByMealType: {
    parameters: {
      query?: {
        /** @description Limit the number of items returned (default: 30) */
        limit?: components['parameters']['limitParam']
        /** @description Skip a number of items for pagination */
        skip?: components['parameters']['skipParam']
      }
      header?: never
      path: {
        /** @description Meal type (Breakfast, Lunch, Dinner, Snack, etc.) */
        mealType: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful operation */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RecipesResponse']
        }
      }
    }
  }
  healthCheck: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description API is healthy */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @example ok */
            status?: string
            /** @example GET */
            method?: string
          }
        }
      }
    }
  }
  generateImage: {
    parameters: {
      query?: {
        /** @description Background color (hex without #) */
        background?: string
        /** @description Text color (hex without #) */
        color?: string
        /** @description Image type */
        type?: 'png' | 'jpeg' | 'webp'
      }
      header?: never
      path: {
        /** @description Image size (e.g., 200x200, 400x300) */
        size: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Generated image */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'image/png': unknown
          'image/jpeg': unknown
          'image/webp': unknown
        }
      }
    }
  }
  generateIcon: {
    parameters: {
      query?: never
      header?: never
      path: {
        /** @description Hash string for generating unique icon */
        hash: string
        /** @description Icon size in pixels */
        size: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Generated icon */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'image/svg+xml': unknown
          'image/png': unknown
        }
      }
    }
  }
}
